pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

def props = new Properties()
def localProps = file('local.properties')
if (localProps.exists()) {
    localProps.withInputStream { props.load(it) }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url = uri('https://jitpack.io') }
        maven {
            url = uri('https://maven.pkg.github.com/facebook/meta-wearables-dat-android')
            credentials {
                username = System.getenv('GITHUB_ACTOR') ?: ''
                password = System.getenv('GITHUB_TOKEN') ?: props.getProperty('github_token', '')
            }
        }
    }
}

rootProject.name = 'GlassesHub'
include ':companion'
